F..
======================================================================
FAIL: test_eval_1 (__main__.TestNetflix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestNetflix.py", line 27, in test_eval_1
    w.getvalue(), "10040:\n2.4\n2.4\n2.4\n0.90\n")
AssertionError: '10040:\n3.9\n2.9\n3.8\n0.90\n' != '10040:\n2.4\n2.4\n2.4\n0.90\n'
  10040:
- 3.9
- 2.9
?   ^
+ 2.4
?   ^
- 3.8
+ 2.4
+ 2.4
  0.90


----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (failures=1)
